const JOURNAL_ABBREVIATIONS = {
    PRD: "PRD",
    JOSS: "JOSS",
    CQG: "CQG",
    PRL: "PRL"
}

const JOURNALS = {
    "Phys. Rev. D": JOURNAL_ABBREVIATIONS.PRD,
    "J. Open Source Softw.": JOURNAL_ABBREVIATIONS.JOSS,
    "Class. Quant. Grav.": JOURNAL_ABBREVIATIONS.CQG,
    "Phys. Rev. Lett.": JOURNAL_ABBREVIATIONS.PRL
}

export { JOURNAL_ABBREVIATIONS, JOURNALS }